class_names = [
    "Pacific Ridley",
    "eastern bluestar",
    "rounded shinleaf",
    "Pale-breasted Thrush",
    "Partridgefoot",
    "Formosan Beauty- berry",
    "Black Girdled Lizard",
    "Smooth-eyed Bushbrown",
    "coastal manroot",
    "Portia tree",
    "Gully Fern",
    "Amethyst Deceiver",
    "Ground-pine",
    "Pink Underwing",
    "Pannaria Wave Moth",
    "Aplomado Falcon",
    "Draparnaud's Glass-snail",
    "Moon Carrot",
    "Hairy Vetchling",
    "Western Banded Gecko",
    "angel's trumpet",
    "Plain Mariposa Lily",
    "Oregon iris",
    "Red-knobbed Coot",
    "Painted Bunting",
    "White-faced Meadowhawk",
    "Vine Hawk-Moth",
    "Horsefly-like Carpenter Bee",
    "Jasmine Moth",
    "Zebra Mussel",
    "Plains Zebra",
    "California Golden Violet",
    "Pennyroyal",
    "Dollarbird",
    "African Clawed Frog",
    "beardlip penstemon",
    "Trumpet Vine Moth",
    "Lesser Black-backed Gull",
    "Pacific Aster",
    "Dark Sailor Beetle",
    "Small-scaled Lizard",
    "Long-crested Eagle",
    "Cackling Goose",
    "European Harvestman",
    "Broad-lined Angle",
    "Domestic Horse",
    "Suffolk Lungwort",
    "white-stemmed milkweed",
    "tamarack",
    "purple-flowered raspberry",
]
